### ISSUE TITLE
Output to stdout instead of file (or allow via option)

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-metadata-manager#15]
Outputting to stdout is more flexible and more standard I think. Easier to work with other tools (like json formatters) and stay agnostic of your current directory.

An option makes sense, though I would default to stdout personally.

**Comment by paterczm** [comment]
Which use cases do you have in mind? Pull can download multiple files. Set and apply (in the works) modify existing file.

**Comment by alechenninger** [comment]
I'd like to use richer comparison tools which is easier when being able to pipe to other formatters and diff utilities without modifying the filesystem.

In general when trying to write scripts to automate using the utility, it's easier to reason about how they can work when I can pipe the output and not have to deal with filesystem.

**Comment by paterczm** [comment]
Pipes are useful, but they don't really fit lbmd command line interface. It was modeled after git and like with git, I don't see sensible use cases (except for diff maybe) for using pipes. Can you give me some concrete examples?

**Comment by alechenninger** [comment]
lbmd pull -e foo --env bar -v 1.2.3 | json_pp > anotherDirectory/foo123.json
diff anotherDirectory/foo.json anotherDirectory/foo123.json
lbmd pull -e foo --env bar -v 1.2.3 | jq '.entityInfo.hooks | map(select(.name == "notificationHook")) | .[0].configuration'

It's not a huge deal, the tool is still useful, it's just a little unfamiliar not to be able to work in stdout.

**Comment by paterczm** [comment]
I see. I can add that feature for git pull when pulling a single entity.
